themename: Devil
# Portal
favicon: image/favicon.ico
nickname: Portgas·D·Asce
motto: Nobody can save you except yourself.
## Links
links:
  LeetCode: https://leetcode.com/portgas-d-asce/
  Github: https://github.com/Portgas-D-Asce

## Research Interests
interests:
  Programming:
    introduce: 123
  Mathematics:
    introduce: 456
  Computer Vision:
    introduce: 789
  About Me:
    introduce: 非技术，关于个人的一些东西。

# 分类介绍
# categories
categories:
#################################################################
  C/C++: 
    introduce: C/C++专栏。
    interest: Programming
  Data Structure & Algorithm: 
    introduce: 涵盖：数据结构 & 算法 & 刷题套路。
    interest: Programming
  Linux: 
    introduce: Linux从入门到放弃。
    interest: Programming
  Hexo: 
    introduce: 从零开始，打造一款干净、整洁的个人博客。
    interest: Programming
  VSCode: 
    introduce: VSCode使用相关问题
    interest: Programming
  Git: 
    introduce:
    interest: Programming
  CMake: 
    introduce:
    interest: Programming
  Tools & Skills:
    introduce:
    interest: Programming
  Python: 
    introduce: 
    interest:
  gcc/g++: 
    introduce: 
    interest: Programming
##
  Advanced Mathematics:
    introduce: 高数
    interest: Mathematics
  Linear Algebra:
    introduce: 线性代数
    interest: Mathematics
  Probability Theory:
    introduce: 概率论
    interest: Mathematics
  Numerical Analysis:
    introduce: 数值分析
    interest: Mathematics
  Convex Optimization:
    introduce: 凸优化
    interest: Mathematics
##
  Image Processing:
    introduce: 使用 libpng 实现各种图像处理操作。
    interest: Computer Vision
  Structure from Motion:
    introduce: 
    interest: Computer Vision
##
  Profile:
    introduce: 个人简介
    interest: About Me
  Comic: 
    introduce: 那些年，那些追过的漫
    interest: About Me
  Book:
    introduce: 
    interest: About Me
  Fitness:
    introduce: 健身最难的是什么？坚持！！！
    interest: About Me
  Store:
    introduce: 我的杂货铺
    interest: About Me

#年度归档
archives:
  2020: 
    introduce: 最后的倔强。

#模块开关及其配置信息
#copyright
copyright:
  enable: true
  copyright: 码字不易，尊重版权，转载请注明出处！
  disclaimer: 本文部分信息搜集自互联网，如若侵犯了您的相关权益，请告知，本站将立刻处理。

#top置顶
top:
  enable: true

#reproduce转载
reproduce:
  enable: true

#wordcount字数统计
wordcount: 
  enable: true

#toc目录
toc:
  enable: true

#recent近期发表
recent:
  enable: true
  num: 5

#categories分类
category:
  enable: true

#tags标签云
tag:
  enable: true

#archives日期归档
archive:
  enable: true

#APlayer音乐播放器
meting:
  enable: true
  url: https://y.qq.com/n/yqq/playlist/7679023489.html
#Gitalk
gitalk:
  enable: true #用来做启用判断可以不用
  owner: Portgas-D-Asce #Github 用户名,
  repo: Portgas-D-Asce.github.io #储存评论issue的github仓库名
  admin: Portgas-D-Asce #Github 用户名,
  clientID: 44d043e14172988e852d #`Github Application clientID`
  clientSecret: 8e341ed76d50a62e8716180d55d2099782a2aa59 #`Github Application clientSecret`