themename: Devil
# Portal
favicon: image/favicon.ico
nickname: Portgas·D·Asce
motto: Nobody can save you except yourself.
## Links
links:
  LeetCode: https://leetcode.com/portgas-d-asce/
  Github: https://github.com/Portgas-D-Asce

## Research Interests
interests:
  Computer Science:
    introduce: 123
  Math:
    introduce: 456
  Computer Vision:
    introduce: 789
  Machine Learning:
    introduce: 0
  About Me:
    introduce: 111

# 分类介绍
# categories
categories:
#################################################################
  Ubuntu: 
    introduce: Ubuntu从入门到放弃。
    interest: Computer Science
    url: 
  VSCode: 
    introduce: VSCode使用相关问题
    interest: Computer Science
    url: 
  Hexo: 
    introduce: 从零开始，打造一款干净、整洁的个人博客。
    interest: Computer Science
    url:
  Tool:
    introduce:
    interest: Computer Science
    url:
##
  Python: 
    introduce: 
    interest:
    url:
  C/CXX: 
    introduce: C/C++专栏。
    interest: Computer Science
    url:
  Data Structure & Algorithm: 
    introduce: 
    interest: Computer Science
    url: 
##
  Advanced Mathematics:
    introduce: 高数
    interest: Math
    url: 
  Linear Algebra:
    introduce: 线性代数
    interest: Math
    url: 
  Probability Theory:
    introduce: 概率论
    interest: Math
    url: 
  Numerical Analysis:
    introduce: 数值分析
    interest: Math
    url: 
  Convex Optimization:
    introduce: 凸优化
    interest: Math
    url: 
##
  Structure from Motion:
    introduce: 
    interest: Computer Vision
    url: 
  Image Processing:
    introduce: 
    interest: Computer Vision
    url: 
##
  Profile:
    introduce: 个人简介
    interest: About Me
    url:
  Comic: 
    introduce: 那些年，那些追过的漫
    interest: About Me
    url:
  Store:
    introduce: 我的杂货铺
    interest: About Me
    url:

#模块开关及其配置信息
#copyright
copyright:
  enable: true
  copyright: 码字不易，尊重版权，转载请注明出处！
  disclaimer: 本文部分信息搜集自互联网，如若侵犯了您的相关权益，请告知，本站将立刻处理。

#top置顶
top:
  enable: true

#reproduce转载
reproduce:
  enable: true

#wordcount字数统计
wordcount: 
  enable: true

#toc目录
toc:
  enable: true

#recent近期发表
recent:
  enable: true
  num: 10

#categories分类
category:
  enable: true

#tags标签云
tag:
  enable: true

#archives日期归档
archive:
  enable: true

#APlayer音乐播放器
meting:
  enable: true
  url: https://y.qq.com/n/yqq/playlist/7679023489.html
#Gitalk
gitalk:
  enable: true #用来做启用判断可以不用
  owner: Portgas-D-Asce #Github 用户名,
  repo: Portgas-D-Asce.github.io #储存评论issue的github仓库名
  admin: Portgas-D-Asce #Github 用户名,
  clientID: 44d043e14172988e852d #`Github Application clientID`
  clientSecret: 8e341ed76d50a62e8716180d55d2099782a2aa59 #`Github Application clientSecret`